description = """
Crates in the project fall into one of these categories.

* Application Interfaces
* Language bindings
* API Bindings
* Core and Utilities
* Features

We generally strive towards extracting features into separate crates to keep the `bitwarden-core`
crate as lean as possible. This has multiple benefits such as faster compile-time and clear ownership of features.
"""

[[categories]]
category = "applications"
title = "Application Interfaces"
description = "An application interface collects the various features relevant for a given Bitwarden product, e.g. Password Manager, or Secrets Manager, into a single easy-to-use crate for that particular product."

[[categories]]
category = "bindings"
title = "Language bindings"
description = "Bindings provide bindings for other projects by targeting `wasm`, `iOS`, and `Android`. The two mobile targets are built using UniFFI."

[[categories]]
category = "apis"
title = "API bindings"
description = "API bindings for Bitwarden server services. Can be either auto generated or hand-written. These crates should only contain server bindings and no business logic."

[[categories]]
category = "core"
title = "Core and Utilities"
description = "Foundational modules and helpers."

[[categories]]
category = "features"
title = "Features"
description = "Core business logic split into separate feature oriented crates. When adding new functionality it should be added to an existing feature crate or a new feature crate should be created."
