[bindings.kotlin]
package_name = "com.bitwarden.auth"
generate_immutable_records = true
android = true

[bindings.swift]
ffi_module_name = "BitwardenAuthFFI"
module_name = "BitwardenAuth"
generate_immutable_records = true