[package]
name = "bitwarden-ssh"
description = """
Internal crate for the bitwarden crate. Do not use.
"""
exclude = ["/resources"]

version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license-file.workspace = true
keywords.workspace = true

[features]
ecdsa-keys = [] # Allow ECDSA key generation and import at runtime (disabled by default)
wasm = [
    "bitwarden-error/wasm",
    "dep:tsify",
    "dep:wasm-bindgen",
    "getrandom/wasm_js",
] # WASM support
uniffi = ["dep:uniffi"] # Uniffi bindings

[dependencies]
bitwarden-error = { workspace = true }
bitwarden-vault = { workspace = true }
block-padding = { version = "=0.4.2" }
ed25519 = { version = "3.0.0-rc.2", features = ["pkcs8"] }
ed25519-dalek = { version = "=3.0.0-pre.6", features = ["alloc", "pkcs8"] }
getrandom = { version = "0.4" }
p256 = { version = "0.14.0-rc.7", features = ["alloc", "pkcs8"], default-features = false }
p384 = { version = "0.14.0-rc.7", features = ["alloc", "pkcs8"], default-features = false }
p521 = { version = "0.14.0-rc.7", features = ["alloc", "pkcs8"], default-features = false }
pem-rfc7468 = "1.0.0-rc.3"
pkcs8 = { version = "=0.11.0-rc.11", features = ["encryption"] }
rand = "0.10.0-rc.5"
rand_core = "0.10.0-rc.2"
rsa =  "0.10.0-rc.10"
serde.workspace = true
ssh-cipher = "0.3.0-rc.4"
ssh-key = { version = "0.7.0-rc.4", features = [
    "ed25519",
    "encryption",
    "p256",
    "p384",
    "p521",
    "rsa",
], default-features = false }
thiserror = { workspace = true }
tsify = { workspace = true, optional = true }
uniffi = { workspace = true, optional = true }
wasm-bindgen = { workspace = true, optional = true }

[dev-dependencies]
rand_chacha = "0.10.0-rc.1"

[lints]
workspace = true
