[package]
name = "bitwarden-noise"
description = """
Internal crate for bitwarden NOISE protocol tunnel. Do not use.
"""

version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
homepage.workspace = true
repository.workspace = true
license-file.workspace = true
readme.workspace = true
keywords.workspace = true

[features]
wasm = ["bitwarden-error/wasm", "dep:tsify", "dep:wasm-bindgen"]

[dependencies]

base64 = "0.22"
bitwarden-error = { workspace = true }
getrandom = { version = "0.2", features = ["js"] }
hkdf = "0.12"
js-sys = { workspace = true }
once_cell = "1.19"
serde.workspace = true
sha2 = "0.10"
snow = "0.9"
thiserror.workspace = true
tsify = { workspace = true, optional = true }
wasm-bindgen = { workspace = true, optional = true }

[lints]
workspace = true
