[bindings.kotlin]
package_name = "com.bitwarden.policies"
generate_immutable_records = true
android = true

[bindings.swift]
ffi_module_name = "BitwardenPoliciesFFI"
module_name = "BitwardenPolicies"
generate_immutable_records = true
